amcl:
  min_particles:             100
  max_particles:             500
  kld_err:                   0.01
  kld_z:                     0.99
  # update_min_d:              0.25
  # update_min_a:              0.2
  transform_tolerance:       1.0
  # recovery_alpha_slow:       0.15
  # recovery_alpha_fast:       0.5
  # gui_publish_rate:          4.0

  # laser parameters
  # laser_max_beams:           90
  # laser_z_hit:               0.95
  # laser_z_short:             0.1
  # laser_z_max:               0.05
  # laser_z_rand:              0.05
  # laser_sigma_hit:           0.2
  # laser_lambda_short:        0.1
  # laser_model_type:          likelihood_field
  # laser_likelihood_max_dist: 2.0

  # odom parameters
  odom_model_type:           diff-corrected
  odom_alpha1:               0.05
  odom_alpha2:               0.005
  odom_alpha3:               0.005
  odom_alpha4:               0.05
  odom_frame_id:             odom
  base_frame_id:             base_footprint

