global_costmap:
    global_frame: map
    robot_base_frame: base_link
    static_map: true
    footprint: [[-0.15, .15], [0.45, .15], [0.45, -0.15], [-0.15, -0.15]]
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
        sensor_frame: laser
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true

local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    width: 2.0
    height: 2.0
    update_frequency: 2.0
    publish_frequency: 2.0
    rolling_window: true
    footprint: [[-0.15, .15], [0.45, .15], [0.45, -0.15], [-0.15, -0.15]]
    inflation_radius: 0.1
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
        sensor_frame: laser
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true

